title: Yeong Heun
description: Computer Engineering Student
site_title: Yeong Heun | Computer Engineering Student

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: yeongheun
blog_url: https://velog.io/@0nee/posts
email: iyoungheuni@gmail.com
keybase_username: yeongheun
twitter_username: yeongheun
reddit_username: yeongheun

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 